/*

MIT License

Copyright (c) Jeff Campbell

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

namespace JCMG.Genesis.Editor
{
	/// <summary>
	/// Helper class for comments
	/// </summary>
	public static class CommentTools
	{
		// Comment
		private const string AUTOGENERATED_HEADER_COMMENT =
			@"//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool (Genesis).
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		private const string AUTOGENERATED_HEADER_COMMENT_VERSION_FORMAT =
			@"//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool (Genesis v{0}, branch:{1}).
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		public static string GetCommentHeader()
		{
			return AUTOGENERATED_HEADER_COMMENT;
		}

		public static string GetCommentHeaderWithVersion()
		{
			return string.Format(
				AUTOGENERATED_HEADER_COMMENT_VERSION_FORMAT,
				VersionConstants.VERSION,
				VersionConstants.GIT_BRANCH);
		}
	}
}
