namespace Genesis.Plugin
{
	/// <summary>
	/// Helper class for comments
	/// </summary>
	public static class CommentTools
	{
		// Comment
		private const string AUTOGENERATED_HEADER_COMMENT =
			@"//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool (Genesis).
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		private const string AUTOGENERATED_HEADER_COMMENT_VERSION_FORMAT =
			@"//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by a tool (Genesis v{0}).
//
//
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		public static string GetCommentHeader()
		{
			return AUTOGENERATED_HEADER_COMMENT;
		}

		public static string GetCommentHeaderWithVersion()
		{
			return string.Format(
				AUTOGENERATED_HEADER_COMMENT_VERSION_FORMAT,
				VersionConstants.ASSEMBLY_SEM_VER);
		}
	}
}
